server:
  port: 9090
  ip: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunyi?serverTimezone=GMT%2b8
    username: root
    password: admin123
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml